import java.text.SimpleDateFormat

plugins {
    id 'java-library'
    id 'application'
    id 'net.nemerosa.versioning' version '3.1.0'
    id 'com.vanniktech.maven.publish' version '0.34.0'
}

description = 'NightscoutConnector is a little library to connect to a Nightscout server and retrieve blood glucose values'

Date buildTimeAndDate = new Date()
ext {
    moduleName      = 'eu.hansolo.nightscoutconnector'
    buildDate       = new SimpleDateFormat('yyyy-MM-dd').format(buildTimeAndDate)
    buildTime       = new SimpleDateFormat('HH:mm:ss.SSSZ').format(buildTimeAndDate)
    ciOssrhUsername = System.getenv('OSSRH_USERNAME')
    ciOssrhPassword = System.getenv('OSSRH_PASSWORD')
    ciGHUser        = System.getenv('GH_USER')
    ciGHToken       = System.getenv('GH_TOKEN')
    gpgkey          = System.getenv("GPG_PRIVATE_KEY")
    gpgpassphrase   = System.getenv("PASSPHRASE")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'eu.hansolo:toolbox:21.0.31'
    implementation 'com.google.code.gson:gson:2.13.2'

    testImplementation platform('org.junit:junit-bom:5.10.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainModule = 'eu.hansolo.nightscoutconnector'
}

jar {
    from {
        //duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        //configurations.runtimeClasspath.collect {  it.isDirectory() ? it : zipTree(it)  }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    manifest {
        attributes(
                'Built-By'              : System.properties['user.name'],
                'Created-By'            : System.properties['java.version'] + " (" + System.properties['java.vendor'] + " " + System.properties['java.vm.version'] + ")",
                'Build-Date'            : project.buildDate,
                'Build-Time'            : project.buildTime,
                'Build-Revision'        : versioning.info.commit,
                'Specification-Title'   : project.name,
                'Specification-Version' : project.version,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.version,
                'Bundle-Name'           : project.name,
                'Bundle-License'        : 'https://www.apache.org/licenses/LICENSE-2.0;description=Apache License Version 2.0;link=https://spdx.org/licenses/Apache-2.0.html',
                'Bundle-Description'    : description,
                'Bundle-Version'        : project.version,
                'Bundle-SymbolicName'   : 'eu.hansolo.nightscoutconnector',
                'Export-Package'        : 'eu.hansolo.nightscoutconnector',
                'Class-Path'            : "${project.name}-${project.version}.jar"
                //'Class-Path'            : configurations.runtimeClasspath.files.collect { it.getName() }.join(' ')
        )
    }
}

if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
        tasks.withType(Javadoc) {
            options.addStringOption('Xdoclint:none', '-quiet')
        }
    }
}

// create one jar for the javadoc
tasks.register('javadocJar', Jar) {
    dependsOn tasks.javadoc
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

// create one jar for the source files
tasks.register('sourcesJar', Jar) {
    dependsOn tasks.classes
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

mavenPublishing {
    coordinates("eu.hansolo", "nightscoutconnector", "${version}")

    pom {
        name = "NightScoutConnector"
        description = "NightscoutConnector is a little library to connect to a Nightscout server and retrieve blood glucose values"
        inceptionYear = "2026"
        url = "https://github.com/HanSolo/nightscoutconnector/"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "HanSolo"
                name = "Gerrit Grunwald"
                email = "han.solo@mac.com"
                url = "https://github.com/HanSolo/"
            }
        }
        scm {
            url = "https://github.com/HanSolo/nightscoutconnector/"
            connection = "scm:git:git://github.com/HanSolo/nightscoutconnector.git"
            developerConnection = "scm:git:ssh://git@github.com/HanSolo/nightscoutconnector.git"
        }
    }
}

test {
    useJUnitPlatform()
}